### ISSUE TITLE
Win 10: Plus Key Not Working

### ISSUE THREAD

**Issue by tajmone** [wqferr/palette-maker#1]
Hi @wqferr, first of all thanks for this tool — it's really good for creating quick palettes and color ramps.

The only problem I'm facing is that on Win 10 x64 Italian (with Italian keyboard) the app doesn't work with plus sign <kbd>+</kbd> key (neither from main keyboard nor from the numeric pad). 

The minus key <kbd>-</kbd> works fine (but only from main keyboard, not from numeric pad), and all other key combinations with <kbd>Ctrl</kbd>, <kbd>Shift</kbd> and/or <kbd>Alt</kbd> are working as expected for the minus key — but none with<kbd>+</kbd>.

For some reason, it seems that LOVE is not handling correctly the Italian keyboard layout.

**Comment by wqferr** [comment]
Hey @tajmone ! Thanks for the feedback, good to know you like the tool.
I will definitely take a look at the issue in the next couple of days, but right now I'm kind of stumped with other work I need to do.
I might add a quickfix for now (thinking on an alternate binding which does work) which I'll try to push by tomorrow afternoon. After sunday I will have a lot more free time and will be able to actually try to fix it.

**Comment by tajmone** [comment]
Thanks, there is no hurry; I just thought of letting you know as they problem might affect other locales' keyboards layouts too.

Keep up the good work!

**Comment by wqferr** [comment]
Already working on a fix and other minor tweaks in the unstable branch. As the name suggests, not all features are available or fully functional there, but it should be done by tomorrow afternoon if nothing goes too crazy.
As a sidenote, I recalled the code not being pretty, but oh man... I might need to revisit this project sometime soon just to clean this up.

**Comment by wqferr** [comment]
OK, it's 3 AM but I think I finished it. No reason as to why I didn't wait til tomorrow. In fact I should have, but whatever, I didn't.
Tell me if your problem is still there, I'll try to fix it for real if it isn't solved.
Also, I changed a few commands to make them easier to perform without having to check the cheat sheet every time.

**Comment by tajmone** [comment]
Works perfectly now! And the numeric pad <kbd>+</kbd> and <kbd>-</kbd> keys are reckonized too.

Thanks!

**Comment by tajmone** [comment]
I've added a link to PaletteMaker in a Pixel Art project I'm working on (on and off):

- https://github.com/tajmone/pixel-art-supplies#palettemaker

Not much of a review really, just a link with few introductiory words. But I'll clean it up some time in the future, as I intend to create a well organized section to review third party tools.
